In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df = df.dropna().drop_duplicates()

In [4]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [5]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in df.columns:
    le = LabelEncoder()
    if type(df[col][0]) == str:
        df[col] = le.fit_transform(df[col])
        encoders[col] = le

In [6]:
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,0,2,0,7,76,2,1,1,0,2,1,2,2,0,1,2,0,68
6603,23,76,0,2,0,8,81,2,1,3,1,0,1,2,2,0,1,2,0,69
6604,20,90,2,1,1,6,65,1,1,3,1,2,1,0,2,0,2,2,0,68
6605,10,86,0,0,1,6,91,0,1,2,1,2,0,2,3,0,1,0,0,68
6606,15,67,2,1,1,9,94,2,1,0,2,2,1,2,4,0,2,2,1,64

In [7]:
encoders

{'Parental_Involvement': LabelEncoder(),
 'Access_to_Resources': LabelEncoder(),
 'Extracurricular_Activities': LabelEncoder(),
 'Motivation_Level': LabelEncoder(),
 'Internet_Access': LabelEncoder(),
 'Family_Income': LabelEncoder(),
 'Teacher_Quality': LabelEncoder(),
 'School_Type': LabelEncoder(),
 'Peer_Influence': LabelEncoder(),
 'Learning_Disabilities': LabelEncoder(),
 'Parental_Education_Level': LabelEncoder(),
 'Distance_from_Home': LabelEncoder(),
 'Gender': LabelEncoder()}

In [8]:
X = df.drop(columns=["Exam_Score", "Gender"], axis=1) # i decided to remove gender variable as it is not a very important variable for predicting
y = df["Exam_Score"]

In [9]:
X

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,0,2,0,7,76,2,1,1,0,2,1,2,2,0,1,2
6603,23,76,0,2,0,8,81,2,1,3,1,0,1,2,2,0,1,2
6604,20,90,2,1,1,6,65,1,1,3,1,2,1,0,2,0,2,2
6605,10,86,0,0,1,6,91,0,1,2,1,2,0,2,3,0,1,0
6606,15,67,2,1,1,9,94,2,1,0,2,2,1,2,4,0,2,2

In [10]:
y

0       67
1       61
2       74
3       71
4       70
        ..
6602    68
6603    69
6604    68
6605    68
6606    64
Name: Exam_Score, Length: 6378, dtype: int64

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
X_scaled

array([[ 0.50507871,  0.34452035, -0.25645734, ..., -0.34203471,
         0.14700266,  0.7514487 ],
       [-0.16325988, -1.38710878, -0.25645734, ..., -0.34203471,
        -1.27573324, -0.74022257],
       [ 0.67216335,  1.55666073,  0.89950373, ..., -0.34203471,
         1.56973856,  0.7514487 ],
       ...,
       [ 0.00382477,  0.86400908,  0.89950373, ..., -0.34203471,
         1.56973856,  0.7514487 ],
       [-1.66702171,  0.51768326, -1.41241841, ..., -0.34203471,
         0.14700266, -2.23189385],
       [-0.83159847, -1.12736441,  0.89950373, ..., -0.34203471,
         1.56973856,  0.7514487 ]], shape=(6378, 18))

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

In [14]:
# i tested various ml algorithms but linear regression performed the best

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [22]:
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_test)
mean_squared_error(y_test, y_pred)

6.199304191856236

In [23]:
# accuracy doesn't matter a lot with this model since the student scores could be diverse and what matters more is precision or how close was the predicted value to the student's score, so mean squared error matters more here

model.score(X_test, y_test)

0.6191479573102655

In [24]:
len(X_train)

5102

In [25]:
# i didnt do any hyperparameter tuning because linear regression algorithm is quite simple and doesn't have a lot of hyperparameters, neither i did see a big difference after doing some hyperparameter tuning

In [26]:
y_test[:15]

852     66
298     66
5490    64
6354    60
5000    62
4372    66
4545    70
5831    72
5656    67
5260    68
4601    69
733     68
2695    67
817     70
5176    64
Name: Exam_Score, dtype: int64

In [27]:
y_pred[:15]

array([67.32242998, 65.88488619, 66.22983782, 60.50871633, 62.01669452,
       65.35847894, 69.61703085, 70.5488499 , 66.7181861 , 70.23446504,
       68.86609294, 66.8645088 , 68.13046049, 70.1178561 , 63.69148047])

In [22]:
# we see our values are close

In [28]:
import pickle

with open("model.pkl", "wb") as file:
    pickle.dump(model, file)

with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

In [29]:
# just seeing the label encoded values for making the web app

for col, le in encoders.items():
    mapping = dict(zip(le.classes_, range(len(le.classes_))))
    print(f"Mapping for {col}: {mapping}")

Mapping for Parental_Involvement: {'High': 0, 'Low': 1, 'Medium': 2}
Mapping for Access_to_Resources: {'High': 0, 'Low': 1, 'Medium': 2}
Mapping for Extracurricular_Activities: {'No': 0, 'Yes': 1}
Mapping for Motivation_Level: {'High': 0, 'Low': 1, 'Medium': 2}
Mapping for Internet_Access: {'No': 0, 'Yes': 1}
Mapping for Family_Income: {'High': 0, 'Low': 1, 'Medium': 2}
Mapping for Teacher_Quality: {'High': 0, 'Low': 1, 'Medium': 2}
Mapping for School_Type: {'Private': 0, 'Public': 1}
Mapping for Peer_Influence: {'Negative': 0, 'Neutral': 1, 'Positive': 2}
Mapping for Learning_Disabilities: {'No': 0, 'Yes': 1}
Mapping for Parental_Education_Level: {'College': 0, 'High School': 1, 'Postgraduate': 2}
Mapping for Distance_from_Home: {'Far': 0, 'Moderate': 1, 'Near': 2}
Mapping for Gender: {'Female': 0, 'Male': 1}